;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("anlalysis" "analysis" nil :count 0)
    ("anlaysis" "analysis" nil :count 1)
    ("clinitians" "clinicians" nil :count 0)
    ("confoudning" "confounding" nil :count 0)
    ("contension" "contention" nil :count 0)
    ("defintiions" "definitions" nil :count 0)
    ("defintion" "definition" nil :count 1)
    ("defintions" "definitions" nil :count 0)
    ("differnetial" "differential" nil :count 1)
    ("formulatoin" "formulation" nil :count 1)
    ("hieght" "height" nil :count 0)
    ("hieight" "height" nil :count 0)
    ("highligted" "highlighted" nil :count 0)
    ("higlight" "highlight" nil :count 0)
    ("hte" "the" nil :count 10)
    ("infernece" "inference" nil :count 3)
    ("informatoin" "information" nil :count 0)
    ("invarinat" "invariant" nil :count 0)
    ("juxtiposition" "juxtaposition" nil :count 0)
    ("poterior" "posterior" nil :count 0)
    ("probibalistic" "probabilistic" nil :count 0)
    ("qualtiites" "qualities" nil :count 0)
    ("relationshiop" "relationship" nil :count 1)
    ("reserchers" "researchers" nil :count 0)
    ("restrictiive" "restrictive" nil :count 0)
    ("teh" "the" nil :count 4)
    ("unacknoledged" "unacknowledged" nil :count 0)
    ("uncetainty" "uncertainty" nil :count 0)
   ))

