;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("acknowledgement" "acknowledgment" nil :count 0)
    ("allso" "also" nil :count 0)
    ("anlalysis" "analysis" nil :count 0)
    ("anlaysis" "analysis" nil :count 7)
    ("assumptiosn" "assumptions" nil :count 0)
    ("byprodict" "byproduct" nil :count 0)
    ("clinitians" "clinicians" nil :count 0)
    ("confoudning" "confounding" nil :count 0)
    ("consice" "concise" nil :count 0)
    ("contension" "contention" nil :count 0)
    ("defintiions" "definitions" nil :count 0)
    ("defintion" "definition" nil :count 1)
    ("defintions" "definitions" nil :count 0)
    ("differnetial" "differential" nil :count 1)
    ("discussoin" "discussion" nil :count 0)
    ("emphaisze" "emphasize" nil :count 0)
    ("evalulates" "evaluates" nil :count 0)
    ("formulatoin" "formulation" nil :count 2)
    ("foundatoins" "foundations" nil :count 0)
    ("hieght" "height" nil :count 0)
    ("hieight" "height" nil :count 0)
    ("highligted" "highlighted" nil :count 0)
    ("higlight" "highlight" nil :count 0)
    ("hte" "the" nil :count 15)
    ("identifes" "identifies" nil :count 0)
    ("infernece" "inference" nil :count 5)
    ("informatoin" "information" nil :count 2)
    ("interms" "in terms" nil :count 2)
    ("intorducing" "introducing" nil :count 0)
    ("intriduce" "introduce" nil :count 0)
    ("introuce" "introduce" nil :count 0)
    ("invarinat" "invariant" nil :count 0)
    ("juxtiposition" "juxtaposition" nil :count 1)
    ("poterior" "posterior" nil :count 0)
    ("probibalistic" "probabilistic" nil :count 0)
    ("qualtiites" "qualities" nil :count 0)
    ("relationshiop" "relationship" nil :count 2)
    ("reserchers" "researchers" nil :count 0)
    ("restirctions" "restrictions" nil :count 0)
    ("restrictiive" "restrictive" nil :count 0)
    ("teh" "the" nil :count 5)
    ("thsi" "this" nil :count 0)
    ("unacknoledged" "unacknowledged" nil :count 0)
    ("uncetainty" "uncertainty" nil :count 0)
    ("undientified" "unidentified" nil :count 0)
   ))

